### PR TITLE
fix(katana): block env wrongly updated with cli value

### LINKED ISSUE #1724: [BUG] Katana setting gas price in genesis issues
**Describe the bug**
Gas price settings seems to behave differently when set through genesis file vs cmd line.

**Version**
v0.6.0-alpha.8 and alpha.9

**To Reproduce issue # 1**
Works as expected when set through cmd line (gas price 200gwei)
1. `katana --eth-gas-price 200000000000`
2. Estimate simple transfer `starkli invoke 0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7 transfer 0x1234 100 0 --estimate-only`
Returns `0.002111000000000000 ETH`
3. Execute and retrieve receipt `starkli invoke 0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7 transfer 0x1234 100 0`
The actual fee matches the estimated

Set gas price set through [genesis.json](https://github.com/dojoengine/dojo/files/14794446/genesis.json)
1. `katana --genesis genesis.json`
2. Estimate returns the same `0.002111000000000000 ETH`
3. However, after execution actual fee is `0.0010555 ETH` 
4. Actual fee is always the same regardless of gas price (as if stuck at 100gwei)

**To Reproduce issue # 2**
If gas price is set very low in genesis (ex: 1111), transaction will fail with
`2024-03-28T19:37:09.747421Z  INFO executor: transaction execution failed: transaction max fee (0x10c6693) is too low; min max fee is 0x1d90737bf6800`

However, no failure observed if set through cmd line `katana --eth-gas-price 1111`

### PR DESCRIPTION
**Pull request by kariy**
fix #1724

updated the test to make sure the gas prices doesn't get modified with the cli value in the [`update_block_env`](https://github.com/dojoengine/dojo/blob/ad58e43df7d162736fced6b071d59732183e77fb/crates/katana/core/src/backend/mod.rs#L182) method.

now actual tx execution would result in a similar fee value that you get when doing fee estimation

### CODE REVIEW

**Comment by kariy** [comment]
* **#1745** <a href="https://app.graphite.dev/github/pr/dojoengine/dojo/1745?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1744** <a href="https://app.graphite.dev/github/pr/dojoengine/dojo/1744?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @kariy and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: crates/katana/core/src/backend/mod.rs [hunk 1]
```diff
@@ -179,7 +179,6 @@ impl<EF: ExecutorFactory> Backend<EF> {
 
         block_env.number += 1;
         block_env.timestamp = timestamp;
-        block_env.l1_gas_prices = self.config.env.gas_price.clone();
```
Comment (kariy) [inline crates/katana/core/src/backend/mod.rs:182]: if this line is not removed, the updated tests would fail

**Comment by broody** [comment]
@kariy confirmed issue fixed, thx! Appreciate another alpha release with this
