### PR TITLE
fix(torii): ensure torii doesn't stop on model processor fail

### LINKED ISSUE #1794: Loop fail when using unregistered model
**Describe the bug**
emit and event (i think StoreSetRecord) using unregistered model leads to fail loop in torii with following error
`ERROR tori_core::engine: Getting block. error=no rows returned by a query that expected to return at least one row`

**Expected behavior**
Ignore/warning for unregistered models

**Additional context**
0.6.0

### PR DESCRIPTION
**Pull request by glihm**
# Description

When a model that is not registered is emitted in an event, which can be done simply by calling `world.set_entity` with wrong data.

This causes Torii to fail and be taken in an infinite loop.

## Related issue

Closes #1794.

## Tests

Test will be done in #1679.

## Added to documentation?

- [ ] README.md
- [ ] [Dojo Book](https://github.com/dojoengine/book)
- [x] No documentation needed

## Checklist

- [x] I've formatted my code (`scripts/prettier.sh`, `scripts/rust_fmt.sh`, `scripts/cairo_fmt.sh`)
- [x] I've linted my code (`scripts/clippy.sh`, `scripts/docs.sh`)
- [x] I've commented my code
- [x] I've requested a review after addressing the comments

### CODE REVIEW

File: crates/torii/core/src/engine.rs [hunk 1]
```diff
@@ -404,9 +404,12 @@ impl<P: Provider + Sync> Engine<P> {
 
     async fn process_block(&mut self, block_number: u64, block_timestamp: u64) -> Result<()> {
         for processor in &self.processors.block {
-            processor
+            if let Err(e) = processor
```
Comment (tarrencev) [inline crates/torii/core/src/engine.rs:407]: I just want to make sure, in this case, we should retry the processor, otherwise the indexer will end up in an undefined state. We generally want to panic when we run into something that we can't handle so we can detect it and address the root issue.

Comment (glihm) [reply crates/torii/core/src/engine.rs:407]: Hum, this is actually what we try to solve here. Due to the permission less nature of the world, if someone emit an invalid event by hand, torii will panic forever.

When a processor must be validated, a test suite must be done to ensure it works properly. But when we are in production, if Torii can't handle something it must not panic.

We may then have some control at the world level to ensure that an event is always emitted for a registered model. But we may have other invalid situation such keys that couldn't always be checked on chain.

Comment (Larkooo) [reply crates/torii/core/src/engine.rs:407]: I think maybe we should have some events that could panic and others not? Or have some sort of potential fallback like we previously discussed where, if the event fails, handle the error and try to reconstruct the model schema  without the ModelRegistered event. Not sure how it would be implemented tho

Comment (glihm) [reply crates/torii/core/src/engine.rs:407]: Sorry I wasn't specific on the first comment. Totally agree on the fact that transaction and block processors are not expected to fail and we should retry or even still panicking.

On the event side, we're too subject to wrong data being captured by torii, and by ignoring those torii is ensured to run even if someone does voluntarily something bad on the world emitting wrong event structure.

Comment (glihm) [reply crates/torii/core/src/engine.rs:407]: @tarrencev ok forget my answer, I just didn't see correctly where your comment was pointing to the block processor specifically. My bad on that.

Comment (glihm) [reply crates/torii/core/src/engine.rs]: Fixed in 007b7a151adcc08e59ddf954cd8ab7aa9db0483d where block and transaction processors will still panic if there is a problem with the parsing.
As we're not dependent on the network during the process, I propose to not retry and keep the panic as we had before.
