### PR TITLE
fix: resolves #928 by migrating sozo auth writer to 0.3.0

### LINKED ISSUE #928: [sozo] Migrate auth for new architecture
Migrate sozo auth for the new 0.3.0 Architecture

### PR DESCRIPTION
**Pull request by aymericdelab**
fix #928

### CODE REVIEW

File: crates/sozo/src/commands/auth.rs [hunk 1]
```diff
@@ -22,7 +23,7 @@ pub enum AuthCommand {
         model: String,
 
         #[arg(help = "Name of the system to grant writer access to.")]
-        system: String,
+        system: FieldElement,
```
Comment (tarrencev) [inline crates/sozo/src/commands/auth.rs:26]: Let's rename system here and elsewhere to contract

Comment (aymericdelab) [reply crates/sozo/src/commands/auth.rs]: done !

**Review by tarrencev — APPROVED** [review]
