### PR TITLE
fix(sozo): model get not using prefixes

### LINKED ISSUE #2835: [BUG] Sozo `model get` is not using prefixes
**Description**
there is no prefix parsing for sozo model get 

**To Reproduce**

sozo --profile sepolia model get Account 0x054cb935d86d80b5a0a6e756edf448ab33876d01dd2b07a2a4e63a41e06d0ef5,sstr:"misty" 

will not work but 

sozo --profile sepolia model get Account 0x054cb935d86d80b5a0a6e756edf448ab33876d01dd2b07a
2a4e63a41e06d0ef5,0x6d69737479 

will work

**Expected behavior**

to return the data when a string is passed

### PR DESCRIPTION
**Pull request by emarc99**
# Description

## Related issue

Closes #2835 

## Tests

- [x] Yes
- [ ] No, because they aren't needed
- [ ] No, because I need help

## Added to documentation?

- [ ] README.md
- [ ] [Dojo Book](https://github.com/dojoengine/book)
- [ ] No documentation needed

## Checklist

- [x] I've formatted my code (`scripts/prettier.sh`, `scripts/rust_fmt.sh`, `scripts/cairo_fmt.sh`)
- [ ] I've linted my code (`scripts/clippy.sh`, `scripts/docs.sh`)
- [ ] I've commented my code
- [ ] I've requested a review after addressing the comments

## Summary by CodeRabbit

- **New Features**
	- Enhanced key input handling for model retrieval, now accepting serialized keys with various prefixes.
	- Added support for short string key parsing with `sstr:` prefix.
	- Introduced new fields such as `tag` and `selector` in the manifest for improved entity categorization.

- **Bug Fixes**
	- Improved input parsing for model keys.
	- Added quote trimming for string inputs to enhance flexibility.

- **Improvements**
	- More flexible and robust key specification process for model commands.
	- Updated identifiers and addresses in the manifest for better entity management.
	- Restructured method calls and target addresses in policy configurations for streamlined functionality.

### CODE REVIEW

File: bin/sozo/src/commands/model.rs [hunk 1]
```diff
@@ -109,8 +110,11 @@ hashes, called 'hash' in the following documentation.
 
         #[arg(value_name = "KEYS")]
         #[arg(value_delimiter = ',')]
-        #[arg(help = "Comma seperated values e.g., 0x12345,0x69420,...")]
-        keys: Vec<Felt>,
+        #[arg(help = "Comma separated values e.g., \
+                     0x12345,0x69420,sstr:\"hello\",sstr:\"misty\". Supported prefixes:\n  \
+                     - sstr: A cairo short string\n  \
+                     - no prefix: A cairo felt")]
```
Comment (glihm) [inline bin/sozo/src/commands/model.rs:116]: In the case of the keys, only `one felt long` serialized type are supported (everything that can fit in one felt).

That's great you've only put the `sstr` which is the only one supported actually.

```suggestion
        #[arg(help = "Comma separated values e.g., \
                     0x12345,0x69420,sstr:\"hello\". Supported prefixes:\n  \
                     - sstr: A cairo short string\n  \
                     - no prefix: A cairo felt")]
```

Comment (glihm) [reply bin/sozo/src/commands/model.rs:116]: We may add a check that only this prefix is actually used, wdyt?

File: bin/sozo/src/commands/model.rs [hunk 2]
```diff
@@ -222,3 +230,35 @@ impl ModelArgs {
         })
     }
 }
+
+#[cfg(test)]
+mod tests {
```
Comment (glihm) [inline bin/sozo/src/commands/model.rs:235]: Thank you for thinking about tests.

In the current context, this test should already be covered into the `calldata_decoder` file. We can remove this one. 👍 

You could write a test on the argument though.

**Review by glihm — CHANGES_REQUESTED** [review]
Thank you for taking the time on this @emarc99!

Some comments, please don't hesitate if you have any questions.

File: bin/sozo/src/commands/model.rs (hunk 2 above)
Comment (emarc99) [reply bin/sozo/src/commands/model.rs:235]: Awesome, that'll be the better option. These tests were meant to go away eventually.

**Comment by emarc99** [comment]
> Don't forget to run the `scripts/` for the linter. They are in the repository `scripts/` folder.

Noted, sir.

**Comment by glihm** [comment]
> > Don't forget to run the `scripts/` for the linter. They are in the repository `scripts/` folder.
> 
> Noted, sir.

Hey @emarc99, let me know if you have any blocker on that.

File: crates/dojo/world/src/config/calldata_decoder.rs [hunk 3]
```diff
@@ -161,7 +161,14 @@ pub fn decode_single_calldata(item: &str) -> DecoderResult<Vec<Felt>> {
...
             "u256" => U256CalldataDecoder.decode(value)?,
             "str" => StrCalldataDecoder.decode(value)?,
-            "sstr" => ShortStrCalldataDecoder.decode(value)?,
+            "sstr" => {
+                let value = if value.starts_with('"') && value.ends_with('"') {
+                    value.trim_matches('"')
+                } else {
+                    value
+                };
+                ShortStrCalldataDecoder.decode(value)?
```
Comment (glihm) [inline crates/dojo/world/src/config/calldata_decoder.rs:170]: Wasn't the quotes already taken in account? Would you mind explaining the choice here.
Maybe this should land in `decode` function in case we have some?

File: bin/sozo/src/commands/model.rs (hunk 2 above)
Comment (glihm) [reply bin/sozo/src/commands/model.rs:246]: That's actually good having those here for the command, thank you!

**Review by glihm — COMMENTED** [review]
For the linting, you can use:
```
bash scripts/rust_fmt.sh --fix
```

File: crates/dojo/world/src/config/calldata_decoder.rs (hunk 3 above)
Comment (emarc99) [reply crates/dojo/world/src/config/calldata_decoder.rs:170]: Second part of test kept failing with below error;
```bash
running 1 test
test commands::model::tests::test_model_get_argument_parsing ... FAILED

failures:

---- commands::model::tests::test_model_get_argument_parsing stdout ----
thread 'commands::model::tests::test_model_get_argument_parsing' panicked at bin/sozo/src/commands/model.rs:296:13:assertion `left == right` failed
  left: [0x54cb935d86d80b5a0a6e756edf448ab33876d01dd2b07a2a4e63a41e06d0ef5, 0x226d6973747922]
 right: [0x54cb935d86d80b5a0a6e756edf448ab33876d01dd2b07a2a4e63a41e06d0ef5, 0x6d69737479]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    commands::model::tests::test_model_get_argument_parsing

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 51 filtered out; finished in 1.30s

error: test failed, to rerun pass `--bin sozo`
```

File: bin/sozo/src/commands/model.rs (hunk 2 above)
Comment (emarc99) [reply bin/sozo/src/commands/model.rs:246]: My pleasure, sir.

**Comment by emarc99** [comment]
> For the linting, you can use:
> 
> ```
> bash scripts/rust_fmt.sh --fix
> ```

There's progress with this command. Will apply it soon and pr.

File: crates/dojo/world/src/config/calldata_decoder.rs (hunk 3 above)
Comment (emarc99) [reply crates/dojo/world/src/config/calldata_decoder.rs:170]: The issue wanted below to work. 
``` bash
sozo --profile sepolia model get Account 0x054cb935d86d80b5a0a6e756edf448ab33876d01dd2b07a2a4e63a41e06d0ef5,sstr:"misty"
```
Maybe what was intended was below, without quotes around the short string; if so I'll remove the check for trimming quotes.
``` bash
sozo --profile sepolia model get Account 0x054cb935d86d80b5a0a6e756edf448ab33876d01dd2b07a2a4e63a41e06d0ef5,sstr:misty
```

**Review by glihm — COMMENTED** [review]
Hey @emarc99, thank you for your patience and sorry for the delay.

So lately we have relaxed the keys constraint, so anything can be a key (if it's serializable). Would you mind updating the PR to support all the prefixes? :)

Also, the quotes shouldn't be an issue, but let me know how it goes.

**Comment by emarc99** [comment]
> Hey @emarc99, thank you for your patience and sorry for the delay.
> 
> So lately we have relaxed the keys constraint, so anything can be a key (if it's serializable). Would you mind updating the PR to support all the prefixes? :)
> 
> Also, the quotes shouldn't be an issue but let me know how it goes.

Alright, I'll update the PR accordingly, sir.

**Comment by glihm** [comment]
> > Hey @emarc99, thank you for your patience and sorry for the delay.
> > So lately we have relaxed the keys constraint, so anything can be a key (if it's serializable). Would you mind updating the PR to support all the prefixes? :)
> > Also, the quotes shouldn't be an issue but let me know how it goes.
> 
> Alright, I'll update the PR accordingly, sir.

Thank you, let me know if you have any questions. 👍

**Comment by glihm** [comment]
All good @emarc99 or do you still need some feedback? Let me know if you're blocked.

**Comment by emarc99** [comment]
> All good @emarc99 or do you still need some feedback? Let me know if you're blocked.

Yea, I am running tests. I'll update in less than 24 hours for some feedback if tests keep failing, sir.

**Comment by emarc99** [comment]
Quick question sir @glihm.
`str:` and `u256:` return 2 or more felts, will the dojo engine know what to do with these keys?

**Comment by glihm** [comment]
> Quick question sir @glihm.
> 
> `str:` and `u256:` return 2 or more felts, will the dojo engine know what to do with these keys?
> 
> 
> 
> I know the magic is happening in `crates\sozo\ops\src\model.rs`

Yes with latest changes keys are not limited. So all prefixes are supported. The important point is having the he correct serialization, which is handled by the prefixes. 👍

File: crates/dojo/world/src/config/calldata_decoder.rs (hunk 3 above)
Comment (glihm) [reply crates/dojo/world/src/config/calldata_decoder.rs:233]: We need the `"` to make sure strings with spaces are actually included. So `sstr:bla bla` is not supported without `"`. So it is important to have them.

**Review by glihm — COMMENTED** [review]
Thank you @emarc99, you may also have look with new changes on the sozo calldata which is now without `,`. To be consistent with the other part of the stack.

**Comment by emarc99** [comment]
> Thank you @emarc99, you may also have look with new changes on the sozo calldata which is now without `,`. To be consistent with the other part of the stack.

Will look into that asap!

**Review by glihm — APPROVED** [review]
Thank you @emarc99 for the work here.

**Comment by emarc99** [comment]
> Thank you @emarc99 for the work here.

Thanks for the chance, sir. Would've taken me longer to implement the new changes.
Also studying your final code for learning.
